### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by joshuansu0897** [rbren/rss-parser#144]
Hi,
thanks for your great job!

i try to feed this rss in node.js. i use *@arrows/worker* because I need to follow several RSS feeds at the same time
```
http://autokp.podfm.ru/my/rss/rss.xml
http://www.cre8media.net/podcastfeeds/internationalagilityfestival.xml
https://anchor.fm/s/1657d30/podcast/rss
http://feeds.soundcloud.com/users/soundcloud:users:106810700/sounds.rss
http://mm324.xsrv.jp/wp/feed/podcast/
https://anchor.fm/s/1f8504c/podcast/rss
https://radiotalk.jp/rss/b93e87cf1a68d065
http://www.ximalaya.com/album/15745690.xml
https://anchor.fm/s/9e5d3c4/podcast/rss
http://atsusource.wp.xdomain.jp/feed/podcast/
https://podster.fm/rss.xml?pid=41452
https://syncretisme.podomatic.com/rss2.xml
```
but I always receive this error
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:143:11)
    at request (http.js:44:10)
    at get (http.js:48:15)
    at /home/joshuansu/Documents/Trabajo/jifcam.rss/node_modules/rss-parser/lib/parser.js:76:17
    at new Promise (<anonymous>)
    at Parser.parseURL (/home/joshuansu/Documents/Trabajo/jifcam.rss/node_modules/rss-parser/lib/parser.js:75:16)
    at helper (/home/joshuansu/Documents/Trabajo/jifcam.rss/src/utils/workerArrow.js:10:25)
    at MessagePort.<anonymous> (/home/joshuansu/Documents/Trabajo/jifcam.rss/node_modules/@arrows/worker/work.js:20:36)
    at MessagePort.emit (events.js:210:5)
    at MessagePort.onmessage (internal/worker/io.js:70:8) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

**Comment by rbren** [comment]
I think the relevant line is here: https://github.com/rbren/rss-parser/blob/55f947ee18ab14896ec284cc784efeb25e59c628/lib/parser.js#L72

does your feed URL maybe start with whitespace? If `url.indexOf('https')` returns 0, it should work.

**Comment by rbren** [comment]
Closing this, pending additional info.

**Comment by rowanu** [comment]
FWIW found this issue due to same error; it was the leading whitespace 😅(from the ©️ 🍝)

thanks @rbren!
