### ISSUE TITLE
Why 403 code in Camelcamelcamel RSS?

### ISSUE THREAD

**Issue by ardimaunahan** [rbren/rss-parser#154]
Can someone help me how to resolve the 403 error when parsing this URL: https://camelcamelcamel.com/popular.xml?deal=1

```
(node:14359) UnhandledPromiseRejectionWarning: Error: Status code 403
    at ClientRequest.<anonymous> (/home/ubuntu/DevHome/Node/product-price-history-service/node_modules/rss-parser/lib/parser.js:93:25)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:476:22)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
```

I ran the code in Ubuntu 18.04 with Node 12.6.1. Note that is working in Windows 10 Node 12.6.0. 
I already tried setting the headers as well but still no success:
```
const parser = new Parser({
    headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36'
    }
});

let feed = await parser.parseURL('http://camelcamelcamel.com/popular.xml?deal=1');
```

Any tips will be highly appreciated. Thanks.

**Comment by rbren** [comment]
Likely not an issue with the library, but with user-agent etc sniffing on the server side. I'd continue experimenting with the request options.
