### ISSUE TITLE
Inappropriately located doctype declaration

### ISSUE THREAD

**Issue by jlubeck** [rbren/rss-parser#180]
I'm getting that error when using `parseURL` on this url: `https://qalerts.app/data/rss/posts.rss`

Full stacktrace

```
Error: Inappropriately located doctype declaration
Line: 1
Column: 9
Char: E
    at error (/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/node_modules/sax/lib/sax.js:1104:15)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/node_modules/xml2js/lib/parser.js:5:59)
    at /node_modules/rss-parser/lib/parser.js:32:22
    at new Promise (<anonymous>)
    at Parser.parseString (/node_modules/rss-parser/lib/parser.js:31:16)
    at IncomingMessage.<anonymous> (/node_modules/rss-parser/lib/parser.js:101:23)
    at IncomingMessage.emit (events.js:228:7)
```

**Comment by rbren** [comment]
This is probably an issue with the XML feed, and not with this library. I would suggest contacting qalerts.app.
