### ISSUE TITLE
Error: Status code 404

### ISSUE THREAD

**Issue by mistermemer** [rbren/rss-parser#210]
Uh guys I am getting an error Unhandlerpromiserejections warning: Error: Status code 404.
When trying to parseURL please help md

**Comment by juanfernandes** [comment]
I just started getting this error too - I haven't changed any code. 

`> Status code 404

`Error` was thrown:
    Error: Status code 404
        at ClientRequest.<anonymous> (/Users/juanfernandes/Sites/websitename.com/node_modules/rss-parser/lib/parser.js:88:25)
        at Object.onceWrapper (events.js:422:26)
        at ClientRequest.emit (events.js:315:20)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
        at TLSSocket.socketOnData (_http_client.js:509:22)
        at TLSSocket.emit (events.js:315:20)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:284:9)
        at TLSSocket.Readable.push (_stream_readable.js:223:10)`

**Comment by rbren** [comment]
This is an issue with the URL you're trying to parse - it is now returning a 404. It's not an issue with this library.
