### ISSUE TITLE
Does not work in Bun

### ISSUE THREAD

**Issue by bboynton97** [rbren/rss-parser#257]
I'm using this package with Node no problem. I'm currently trying to migrate to Bun and when using it as a js runtime, rss-parser fails.

```
!!! Failed to parse rss for Business Wars
646 |     if (parser.trackPosition) {
647 |       er += '\nLine: ' + parser.line +
648 |         '\nColumn: ' + parser.column +
649 |         '\nChar: ' + parser.c
650 |     }
651 |     er = new Error(er)
             ^
error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: ߋ
      at error (/Users/braelynboynton/Developer/shopwithus/services/api/node_modules/sax/lib/sax.js:651:9)
      at strictFail (/Users/braelynboynton/Developer/shopwithus/services/api/node_modules/sax/lib/sax.js:677:6)
      at beginWhiteSpace (/Users/braelynboynton/Developer/shopwithus/services/api/node_modules/sax/lib/sax.js:951:6)
      at write (/Users/braelynboynton/Developer/shopwithus/services/api/node_modules/sax/lib/sax.js:1006:10)
      at /Users/braelynboynton/Developer/shopwithus/services/api/node_modules/xml2js/lib/parser.js:323:15
      at /Users/braelynboynton/Developer/shopwithus/services/api/node_modules/xml2js/lib/parser.js:5:55
      at /Users/braelynboynton/Developer/shopwithus/services/api/node_modules/rss-parser/lib/parser.js:33:6
      at new Promise (:1:20)
      at parseString (/Users/braelynboynton/Developer/shopwithus/services/api/node_modules/rss-parser/lib/parser.js:32:15)
      at /Users/braelynboynton/Developer/shopwithus/services/api/node_modules/rss-parser/lib/parser.js:96:17
      at endReadableNT (node:stream:2387:52)
      at processTicksAndRejections (:1:2602)
⚡️[job]: No episodes ready to link

```

**Comment by emilianomon** [comment]
Same issue here.

**Comment by muhrifqii** [comment]
have you found any solution or workaround for this? @bboynton97 @emilianomon
